### ISSUE TITLE
ポイント

### ISSUE THREAD

**Issue by Haramaki0326** [Haramaki0326/react-docker-sample#1]
# 基本の考え
- Dockerコンテナは`node` ベース
- Cloneした時点でダウンロードできるファイルは以下
    - `src`
    - `package.json`
    - `dockerfile` (本番用コンテナ)
    - `dockerfile.dev` (開発用コンテナ)
    - `docker-compose.yml`
    - ※ 以下に述べるように、`node_modules` は
        - Git管理をしない
        - ホスト側に入れない
        - Dockerのvolumeにマウントして管理する
- Cloneしてきたpackage.jsonをコンテナに`COPY`してから、nodeコンテナ内で`npm install`を行い必要な`node_modules`をコンテナ内にインストールする（※ ホスト側とはバインドしない）
- （開発環境における）react自体の実行は`create-react-app`付属の開発サーバを立ち上げる（本番用では別途nginxなどのWebサーバをホストする必要あり）
    - `npm run start`（実際の呼び出しコードは`react-scripts start`）で開発サーバを立ち上げる

# ホットリロードの有効化
`docker-compose.yml`
``` yml
    environment:
      - WATCHPACK_POLLING=true
```

# `node_modules`の扱い
- [参考：VSCode&Docker Volumeにおけるnode_modules問題を解決する](https://zenn.dev/foolishell/articles/3d327557af3554)
``` yml
    volumes:
      - type: bind
        source: ./
        target: /app
      - type: volume
        source: node-modules
        target: /app/node_modules
```
